name: Update Deps

on:
  schedule:
    # Запускается каждый день в 21:00 UTC (это 00:00 по Москве)
    - cron: '0 21 * * *'
  workflow_dispatch: # возможность запустить вручную из вкладки Actions

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - name: Update deps
        run: bun update

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add bun.lock package.json
          git diff --cached --quiet || git commit -m "chore: update bun dependencies"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}